spring.application.name=Chungbuk
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# TourAPI ??
spring.config.import=optional:classpath:application-secret.properties

tour-api.base-url=https://apis.data.go.kr/B551011/KorService2
tour-api.mobile-os=ETC
tour-api.mobile-app=ChungbukTravel
tour-api.response-type=json

# Swagger (springdoc-openapi)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha